declare module 'framer-motion' {
  export const motion: any;
  export const AnimatePresence: any;
  export const LayoutGroup: any;
  export const MotionConfig: any;
  export const domAnimation: any;
  export const domMax: any;
  export const m: any;
  export const LazyMotion: any;
  export const useAnimation: any;
  export const useAnimationControls: any;
  export const useInView: any;
  export const useMotionValue: any;
  export const useReducedMotion: any;
  export const useScroll: any;
  export const useSpring: any;
  export const useTransform: any;
  export const useVelocity: any;
}